name:                moffy-samples-gtk4-run
version:             0.1.0.0
github:              "YoshikuniJujo/moffy-samples-gtk4-run"
license:             BSD-3-Clause
author:              "Yoshikuni Jujo"
maintainer:          "yoshikuni.jujo@gmail.com"
copyright:           "Copyright (c) 2023 Yoshikuni Jujo"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Package to run moffy samples - Gtk4 version
category:            Control

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YoshikuniJujo/moffy-samples-gtk4-run#readme>

dependencies:
- base >= 4.7 && < 5
- stm
- text
- time
- random
- moffy
- moffy-samples-events
- type-set
- type-flip
- c-enum
- c-struct
- exception-hierarchy
- simple-cairo
- simple-pango
- union-color

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  pkg-config-dependencies:
    - gtk4

tests:
  moffy-samples-gtk4-run-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - moffy-samples-gtk4-run
